CREATE FUNCTION hashint1(int1) RETURNS int4 IMMUTABLE STRICT LANGUAGE C AS '$libdir/uint', 'hashint1';
CREATE FUNCTION hashu8(u8) RETURNS int4 IMMUTABLE STRICT LANGUAGE C AS '$libdir/uint', 'hashu8';
CREATE FUNCTION hashu16(u16) RETURNS int4 IMMUTABLE STRICT LANGUAGE C AS '$libdir/uint', 'hashu16';
CREATE FUNCTION hashu32(u32) RETURNS int4 IMMUTABLE STRICT LANGUAGE C AS '$libdir/uint', 'hashu32';
CREATE FUNCTION hashu64(u64) RETURNS int4 IMMUTABLE STRICT LANGUAGE C AS '$libdir/uint', 'hashu64';
